# -*- coding: utf-8 -*-
"""관찰 AI 상태 상수 — PyQt/DBManager 비의존.

DBManager.OBS_AI_STATUS_* 와 동일 값. Stage3·ApplicationService·서버가 공유한다.
"""

from __future__ import annotations

OBS_AI_STATUS_PARENT_CD = "OA01"

OBS_AI_STATUS_NONE = "NONE"
OBS_AI_STATUS_PENDING = "PENDING"
OBS_AI_STATUS_COMPLETED = "COMPLETED"
OBS_AI_STATUS_CONFIRMED = "CONFIRMED"
OBS_AI_STATUS_HOLD = "HOLD"
OBS_AI_STATUS_FAILED = "FAILED"
OBS_AI_STATUS_ANALYZING = "ANALYZING"
OBS_AI_STATUS_ANALYZED = "ANALYZED"
OBS_AI_STATUS_REVIEW_REQUIRED = "REVIEW_REQUIRED"

OBS_AI_STATUS_VALUES = frozenset(
    {
        OBS_AI_STATUS_NONE,
        OBS_AI_STATUS_PENDING,
        OBS_AI_STATUS_COMPLETED,
        OBS_AI_STATUS_CONFIRMED,
        OBS_AI_STATUS_HOLD,
        OBS_AI_STATUS_FAILED,
        OBS_AI_STATUS_ANALYZING,
        OBS_AI_STATUS_ANALYZED,
        OBS_AI_STATUS_REVIEW_REQUIRED,
    }
)
