# -*- coding: utf-8 -*-
"""주문 Stage 2 상수 — ST01 SSOT · 채번 · 배송유형.

DEC-011 CLOSED: 신규 주문 status_cd = ST010100.
PC 레거시 '10'/'20' 저장 금지.
"""

from __future__ import annotations

ORDER_STATUS_PARENT_CD = "ST01"
ORDER_STATUS_RESERVED_CD = "ST010100"
ORDER_STATUS_CONFIRMED_CD = "ST010200"
ORDER_STATUS_PREP_CD = "ST010300"
ORDER_STATUS_DELIVERED_CD = "ST010400"
ORDER_STATUS_CANCEL_CD = "ST010500"

ORDER_STATUS_LOCKED = frozenset({ORDER_STATUS_DELIVERED_CD, ORDER_STATUS_CANCEL_CD})
ORDER_STATUS_QTY_LOCKED = frozenset({ORDER_STATUS_CONFIRMED_CD, ORDER_STATUS_PREP_CD})
ORDER_STATUS_CANCELABLE = frozenset({ORDER_STATUS_RESERVED_CD, ORDER_STATUS_CONFIRMED_CD})
ORDER_STATUS_SHIPABLE = frozenset({ORDER_STATUS_CONFIRMED_CD, ORDER_STATUS_PREP_CD})

MSG_ORDER_LOCKED_DELIVERED = "배송완료된 주문은 수정할 수 없습니다."
MSG_ORDER_LOCKED_CANCEL = "취소된 주문은 수정할 수 없습니다."
MSG_ORDER_QTY_LOCKED = "주문확정 이후에는 상품/수량을 수정할 수 없습니다."
MSG_ORDER_CONFIRMED_LIMITED = "주문확정 상태에서는 고객·비고·배송정보만 수정할 수 있습니다."
MSG_ORDER_SHIP_ONLY = "배송준비 상태에서는 배송 정보만 수정할 수 있습니다."
MSG_ORDER_CANCEL_FORBIDDEN = "현재 상태에서는 주문을 취소할 수 없습니다."
MSG_ORDER_CONFIRM_FORBIDDEN = "예약접수 상태에서만 주문확정할 수 있습니다."
MSG_ORDER_ALLOC_SPEC_LOCKED = "배정된 상품의 규격은 변경할 수 없습니다."
MSG_ORDER_ALLOC_QTY_BELOW = "배정수량보다 적게 주문수량을 줄일 수 없습니다."
MSG_PARCEL_DEST_QTY = "배송수량은 0보다 커야 합니다."
MSG_PARCEL_DEST_INCOMPLETE = "택배 배송지의 수령인, 연락처, 주소를 입력해 주십시오."
MSG_PARCEL_QTY_OVER = "택배 배송수량이 주문수량을 초과할 수 없습니다."

ORDER_NO_PREFIX = "ORD"
ORDER_NO_SEQ_LEN = 3

ORDER_LIST_PAGE_DEFAULT = 1
ORDER_LIST_PAGE_SIZE_DEFAULT = 20
ORDER_LIST_PAGE_SIZE_MAX = 100

STOCK_STATUS_OPEN = "N"
WAREHOUSE_CD_DEFAULT = "WH01"

SALES_NO_EMPTY = ""

DELIVERY_TP_PARENT_CD = "LO01"
DELIVERY_TP_VISIT_CD = "LO010100"
DELIVERY_TP_PARCEL_CD = "LO010200"
DELIVERY_TP_CARGO_CD = "LO010300"
DELIVERY_TP_DIRECT_CD = "LO010400"

DELIVERY_TP_ADDR_OPTIONAL = frozenset(
    {DELIVERY_TP_VISIT_CD, DELIVERY_TP_DIRECT_CD}
)

SEASON_TYPE_PARENT_CD = "SS01"
FRUIT_ITEM_PARENT_CD = "FR01"
GRADE_PARENT_CD = "GR01"
# SZ01 = 중량(5kg/7.5kg/15kg·포). 배 크기(과이내)는 FR020100.
SIZE_PARENT_CD = "SZ01"
SPEC_PARENT_CD = "SZ01"
PEAR_ITEM_CD = "FR010100"
PEAR_SIZE_PARENT_CD = "FR020100"
WEIGHT_UNIT_KG = "kg"
WEIGHT_UNIT_PACK = "포"
DEFAULT_WEIGHT_KG = 15.0

ITEM_MID_SUFFIX = "00"
VARIETY_CD_LEN = 8

# 고객(m_customer) — PC CustomerRegistrationPopup SSOT
CUSTOMER_ID_PREFIX = "C"
CUSTOMER_ID_DT_FMT = "%y%m%d%H%M%S"
CUSTOMER_TP_CD = "CT01"
CUSTOMER_USE_YN_Y = "Y"
CUSTOMER_ZIP_EMPTY = ""
MSG_CUSTOMER_NAME_MOBILE_REQUIRED = "고객명과 연락처는 필수입니다."
MSG_CUSTOMER_DUPLICATE = "이미 등록된 연락처입니다."
