# -*- coding: utf-8 -*-
"""판매 목록 조회 Core 상수 (Stage 5 · read-only)."""

from __future__ import annotations

from core.order_constants import (
    ORDER_LIST_PAGE_DEFAULT,
    ORDER_LIST_PAGE_SIZE_DEFAULT,
    ORDER_LIST_PAGE_SIZE_MAX,
)
from core.order_ship_constants import SALES_STATUS_CONFIRMED
from core.sales_payment_constants import SALES_STATUS_DRAFT

SALES_LIST_PAGE_DEFAULT = ORDER_LIST_PAGE_DEFAULT
SALES_LIST_PAGE_SIZE_DEFAULT = ORDER_LIST_PAGE_SIZE_DEFAULT
SALES_LIST_PAGE_SIZE_MAX = ORDER_LIST_PAGE_SIZE_MAX

SALES_SOURCE_AUCTION_RT = "AUCTION_RT"

PAYMENT_STATUS_UNPAID = "UNPAID"
PAYMENT_STATUS_PARTIAL = "PARTIAL"
PAYMENT_STATUS_PAID = "PAID"

PAYMENT_STATUS_FILTER_VALUES = frozenset(
    {PAYMENT_STATUS_UNPAID, PAYMENT_STATUS_PARTIAL, PAYMENT_STATUS_PAID}
)

SALES_STATUS_FILTER_VALUES = frozenset({SALES_STATUS_CONFIRMED, SALES_STATUS_DRAFT})

MSG_SALES_STATUS_INVALID = "판매상태 필터가 올바르지 않습니다."
MSG_PAYMENT_STATUS_INVALID = "수금상태 필터가 올바르지 않습니다."
