# -*- coding: utf-8 -*-
"""판매분류 3축(SA01/SA02/SA03) 상수 · SS01→SA02 매핑 (S2A).

실제 판매 INSERT 승계는 S2C. 이번 모듈은 계약·검증·매핑 SSOT만.
"""

from __future__ import annotations

# --- Parent ---
SALES_TYPE_PARENT_CD = "SA01"
SALES_CATEGORY_PARENT_CD = "SA02"
SALES_ROUTE_PARENT_CD = "SA03"

LABEL_SALES_TYPE_PARENT = "판매유형"
LABEL_SALES_CATEGORY_PARENT = "판매구분"
LABEL_SALES_ROUTE_PARENT = "판매경로"

# --- SA01 판매유형 ---
SALES_TYPE_RETAIL = "SA010100"
SALES_TYPE_WHOLESALE = "SA010200"
SALES_TYPE_EXPORT = "SA010300"

LABEL_SALES_TYPE_RETAIL = "소매"
LABEL_SALES_TYPE_WHOLESALE = "도매"
LABEL_SALES_TYPE_EXPORT = "수출"

SALES_TYPE_ROWS: tuple[tuple[str, str], ...] = (
    (SALES_TYPE_RETAIL, LABEL_SALES_TYPE_RETAIL),
    (SALES_TYPE_WHOLESALE, LABEL_SALES_TYPE_WHOLESALE),
    (SALES_TYPE_EXPORT, LABEL_SALES_TYPE_EXPORT),
)

# --- SA02 판매구분 ---
SALES_CATEGORY_NORMAL = "SA020100"
SALES_CATEGORY_CHUSEOK = "SA020200"
SALES_CATEGORY_SEOLLAL = "SA020300"
SALES_CATEGORY_AUCTION = "SA020400"

LABEL_SALES_CATEGORY_NORMAL = "일반판매"
LABEL_SALES_CATEGORY_CHUSEOK = "추석판매"
LABEL_SALES_CATEGORY_SEOLLAL = "설판매"
LABEL_SALES_CATEGORY_AUCTION = "경매판매"

SALES_CATEGORY_ROWS: tuple[tuple[str, str], ...] = (
    (SALES_CATEGORY_NORMAL, LABEL_SALES_CATEGORY_NORMAL),
    (SALES_CATEGORY_CHUSEOK, LABEL_SALES_CATEGORY_CHUSEOK),
    (SALES_CATEGORY_SEOLLAL, LABEL_SALES_CATEGORY_SEOLLAL),
    (SALES_CATEGORY_AUCTION, LABEL_SALES_CATEGORY_AUCTION),
)

# --- SA03 판매경로 ---
SALES_ROUTE_DIRECT = "SA030100"
SALES_ROUTE_ORDER_SHIP = "SA030200"
SALES_ROUTE_AUCTION = "SA030300"

LABEL_SALES_ROUTE_DIRECT = "직접판매"
LABEL_SALES_ROUTE_ORDER_SHIP = "주문출고"
LABEL_SALES_ROUTE_AUCTION = "경매연동"

SALES_ROUTE_ROWS: tuple[tuple[str, str], ...] = (
    (SALES_ROUTE_DIRECT, LABEL_SALES_ROUTE_DIRECT),
    (SALES_ROUTE_ORDER_SHIP, LABEL_SALES_ROUTE_ORDER_SHIP),
    (SALES_ROUTE_AUCTION, LABEL_SALES_ROUTE_AUCTION),
)

# --- 주문 시즌 SS01 (기존 유지 · 여기선 매핑 키만) ---
SEASON_TYPE_PARENT_CD = "SS01"
SEASON_TYPE_SEOLLAL = "SS010100"
SEASON_TYPE_CHUSEOK = "SS010200"
SEASON_TYPE_NORMAL = "SS010300"

LABEL_SEASON_TYPE_SEOLLAL = "설날"
LABEL_SEASON_TYPE_CHUSEOK = "추석"
LABEL_SEASON_TYPE_NORMAL = "일반"

SEASON_TYPE_ROWS: tuple[tuple[str, str], ...] = (
    (SEASON_TYPE_SEOLLAL, LABEL_SEASON_TYPE_SEOLLAL),
    (SEASON_TYPE_CHUSEOK, LABEL_SEASON_TYPE_CHUSEOK),
    (SEASON_TYPE_NORMAL, LABEL_SEASON_TYPE_NORMAL),
)

# 신규 주문 기본값 (레거시 백필에 쓰지 말 것)
DEFAULT_ORDER_SALES_TYPE_CD = SALES_TYPE_RETAIL
DEFAULT_ORDER_SEASON_TYPE_CD = SEASON_TYPE_NORMAL

SALES_TYPE_CODE_SET: frozenset[str] = frozenset(cd for cd, _ in SALES_TYPE_ROWS)
SEASON_TYPE_CODE_SET: frozenset[str] = frozenset(cd for cd, _ in SEASON_TYPE_ROWS)

# SS01 → SA02 (S2C 승계용). blank/unknown은 None — 일반판매로 추정 금지.
_SEASON_TO_CATEGORY: dict[str, str] = {
    SEASON_TYPE_NORMAL: SALES_CATEGORY_NORMAL,
    SEASON_TYPE_CHUSEOK: SALES_CATEGORY_CHUSEOK,
    SEASON_TYPE_SEOLLAL: SALES_CATEGORY_SEOLLAL,
}


def map_season_type_to_sales_category(season_type_cd: str | None) -> str | None:
    """주문 season_type_cd(SS01) → 판매구분(SA02). 미지/공백은 None."""
    key = str(season_type_cd or "").strip()
    if not key:
        return None
    return _SEASON_TO_CATEGORY.get(key)


# 계약 검증용: (parent_cd, code_cd, code_nm, parent_for_row)
# parent row는 parent_cd=NULL
SALES_CLASS_PARENT_ROWS: tuple[tuple[str, str], ...] = (
    (SALES_TYPE_PARENT_CD, LABEL_SALES_TYPE_PARENT),
    (SALES_CATEGORY_PARENT_CD, LABEL_SALES_CATEGORY_PARENT),
    (SALES_ROUTE_PARENT_CD, LABEL_SALES_ROUTE_PARENT),
)

SALES_CLASS_CHILD_ROWS: tuple[tuple[str, str, str], ...] = (
    *((SALES_TYPE_PARENT_CD, cd, nm) for cd, nm in SALES_TYPE_ROWS),
    *((SALES_CATEGORY_PARENT_CD, cd, nm) for cd, nm in SALES_CATEGORY_ROWS),
    *((SALES_ROUTE_PARENT_CD, cd, nm) for cd, nm in SALES_ROUTE_ROWS),
)
